const fs = require('fs');
const path = 'D:/AndroidProject/Tenancy/app/src/main/java/com/example/tenancy/ui/home/HomeViewModel.kt';
const lines = [
'package com.example.tenancy.ui.home',
'',
'import android.app.Application',
'import android.location.Address',
'import android.location.Geocoder',
'import android.util.Log',
'import androidx.lifecycle.AndroidViewModel',
'import androidx.lifecycle.viewModelScope',
'import com.example.tenancy.data.model.HouseItem',
'import com.example.tenancy.data.model.HouseWithDistance',
'import com.example.tenancy.data.remote.NetworkResult',
'import com.example.tenancy.data.repository.HouseRepository',
'import com.example.tenancy.util.LocationHelper',
'import kotlinx.coroutines.Dispatchers',
'import kotlinx.coroutines.async',
'import kotlinx.coroutines.flow.MutableStateFlow',
'import kotlinx.coroutines.flow.StateFlow',
'import kotlinx.coroutines.flow.asStateFlow',
'import kotlinx.coroutines.launch',
'import kotlinx.coroutines.withContext',
'import kotlinx.coroutines.withTimeoutOrNull',
'import java.util.Locale',
'',
'data class HomeUiState(',
'    val isLoading: Boolean = false,',
'    val locationText: String = "Locating\u2026",',
'    val userLat: Double = 0.0,',
'    val userLng: Double = 0.0,',
'    val isLocating: Boolean = true,',
'    val locationError: String? = null,',
'    val nearbyHouses: List<HouseWithDistance> = emptyList(),',
'    val recommendHouses: List<HouseItem> = emptyList(),',
'    val error: String? = null',
')',
'',
'class HomeViewModel(application: Application) : AndroidViewModel(application) {',
'',
'    private val TAG = "HomeViewModel"',
'    private val repository = HouseRepository()',
'',
'    private val _uiState = MutableStateFlow(HomeUiState())',
'    val uiState: StateFlow<HomeUiState> = _uiState.asStateFlow()',
'',
'    fun loadWithDefaultLocation() {',
'        val defaultLat = 39.9042',
'        val defaultLng = 116.4074',
'        Log.d(TAG, "loadWithDefaultLocation: lat=, lng=")',
'        _uiState.value = _uiState.value.copy(',
'            isLoading = true,',
'            locationText = "Beijing \u00b7 Dongcheng District",',
'            userLat = defaultLat,',
'            userLng = defaultLng,',
'            isLocating = false,',
'            error = null',
'        )',
'        loadHouseData(defaultLat, defaultLng)',
'    }',
'',
'    fun refresh() {',
'        viewModelScope.launch {',
'            _uiState.value = _uiState.value.copy(',
'                isLoading = true,',
'                isLocating = true,',
'                error = null',
'            )',
'            Log.d(TAG, "refresh: starting location + data fetch in parallel")',
'',
'            val locationDeferred = async { fetchLocation() }',
'            val dataDeferred = async { fetchHouseData() }',
'',
'            val (lat, lng, addressText) = locationDeferred.await()',
'            _uiState.value = _uiState.value.copy(',
'                userLat = lat,',
'                userLng = lng,',
'                locationText = addressText,',
'                isLocating = false',
'            )',
'            Log.d(TAG, "refresh: location ->  (, )")',
'',
'            val dataResult = dataDeferred.await()',
'            Log.d(TAG, "refresh: data -> nearby=, recommend=")',
'        }',
'    }',
'',
'    private suspend fun fetchLocation(): Triple<Double, Double, String> {',
'        val location = withTimeoutOrNull(15_000L) {',
'            try {',
'                LocationHelper.getCurrentLocation(getApplication())',
'            } catch (e: SecurityException) {',
'                Log.w(TAG, "fetchLocation: SecurityException", e)',
'                null',
'            } catch (e: Exception) {',
'                Log.w(TAG, "fetchLocation: ", e)',
'                null',
'            }',
'        } ?: run { Log.d(TAG, "fetchLocation: timed out"); null }',
'',
'        return if (location != null) {',
'            val lat = location.latitude',
'            val lng = location.longitude',
'            val address = withTimeoutOrNull(5_000L) {',
'                withContext(Dispatchers.IO) { getAddressFromLocation(lat, lng) }',
'            } ?: String.format(Locale.getDefault(), "%.4f, %.4f", lat, lng)',
'            Triple(lat, lng, address)',
'        } else {',
'            Triple(39.9042, 116.4074, "Beijing \u00b7 Dongcheng District")',
'        }',
'    }',
'',
'    private suspend fun fetchHouseData(): Pair<List<HouseWithDistance>?, List<HouseItem>?> {',
'        val state = _uiState.value',
'        val lat = if (state.userLat != 0.0) state.userLat else 39.9042',
'        val lng = if (state.userLng != 0.0) state.userLng else 116.4074',
'',
'        Log.d(TAG, "fetchHouseData: calling APIs lat=, lng=")',
'',
'        val nearbyDeferred = async {',
'            when (val result = repository.getHousesSortedByDistance(userLat = lat, userLng = lng, pageSize = 10)) {',
'                is NetworkResult.Success -> {',
'                    Log.d(TAG, "fetchHouseData: nearby OK, count=")',
'                    _uiState.value = _uiState.value.copy(nearbyHouses = result.data)',
'                    result.data',
'                }',
'                is NetworkResult.Error -> {',
'                    Log.e(TAG, "fetchHouseData: nearby FAIL code=, msg=")',
'                    _uiState.value = _uiState.value.copy(error = "Nearby: ")',
'                    null',
'                }',
'                is NetworkResult.Loading -> null',
'            }',
'        }',
'',
'        val recommendDeferred = async {',
'            when (val result = repository.getHouses(page = 1, pageSize = 10)) {',
'                is NetworkResult.Success -> {',
'                    val sorted = result.data.sortedByDescending { it.unitPrice ?: 0.0 }',
'                    Log.d(TAG, "fetchHouseData: recommend OK, count=")',
'                    _uiState.value = _uiState.value.copy(',
'                        recommendHouses = sorted,',
'                        isLoading = false,',
'                        error = null',
'                    )',
'                    sorted',
'                }',
'                is NetworkResult.Error -> {',
'                    Log.e(TAG, "fetchHouseData: recommend FAIL code=, msg=")',
'                    _uiState.value = _uiState.value.copy(',
'                        isLoading = false,',
'                        error = "Recommend: "',
'                    )',
'                    null',
'                }',
'                is NetworkResult.Loading -> null',
'            }',
'        }',
'',
'        return Pair(nearbyDeferred.await(), recommendDeferred.await())',
'    }',
'',
'    private fun loadHouseData(lat: Double, lng: Double) {',
'        viewModelScope.launch {',
'            when (val nearbyResult = repository.getHousesSortedByDistance(',
'                userLat = lat, userLng = lng, pageSize = 10',
'            )) {',
'                is NetworkResult.Success -> {',
'                    _uiState.value = _uiState.value.copy(nearbyHouses = nearbyResult.data)',
'                }',
'                is NetworkResult.Error -> {',
'                    _uiState.value = _uiState.value.copy(error = nearbyResult.message)',
'                }',
'                is NetworkResult.Loading -> {}',
'            }',
'',
'            when (val recommendResult = repository.getHouses(page = 1, pageSize = 10)) {',
'                is NetworkResult.Success -> {',
'                    val sorted = recommendResult.data.sortedByDescending { it.unitPrice ?: 0.0 }',
'                    _uiState.value = _uiState.value.copy(',
'                        recommendHouses = sorted,',
'                        isLoading = false,',
'                        error = null',
'                    )',
'                }',
'                is NetworkResult.Error -> {',
'                    _uiState.value = _uiState.value.copy(',
'                        isLoading = false,',
'                        error = recommendResult.message',
'                    )',
'                }',
'                is NetworkResult.Loading -> {}',
'            }',
'        }',
'    }',
'',
'    private suspend fun getAddressFromLocation(lat: Double, lng: Double): String {',
'        return try {',
'            val geocoder = Geocoder(getApplication(), Locale.getDefault())',
'            val addresses: List<Address>? = geocoder.getFromLocation(lat, lng, 1)',
'            if (!addresses.isNullOrEmpty()) {',
'                val address = addresses[0]',
'                val district = address.subAdminArea ?: address.locality ?: ""',
'                val street = address.featureName ?: address.thoroughfare ?: ""',
'                if (street.isNotEmpty()) " \u00b7 " else district.ifEmpty { "Current Location" }',
'            } else {',
'                String.format(Locale.getDefault(), "%.4f, %.4f", lat, lng)',
'            }',
'        } catch (e: Exception) {',
'            String.format(Locale.getDefault(), "%.4f, %.4f", lat, lng)',
'        }',
'    }',
'}',
];
fs.writeFileSync(path, lines.map(l => l.replace(/\$/g, '\x24')).join('\n'), 'utf-8');
console.log('Written OK:', lines.length, 'lines');
